import sqlite3


def create_database():

    conn = sqlite3.connect('computer_science_quiz.db')
    cursor = conn.cursor()

    # Drop table if it exists (optional)
    cursor.execute('DROP TABLE IF EXISTS questions')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS questions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        difficulty TEXT CHECK(difficulty IN ('easy', 'medium', 'difficult')),
        question_text TEXT NOT NULL,
        option1 TEXT NOT NULL,
        option2 TEXT NOT NULL,
        option3 TEXT NOT NULL,
        option4 TEXT NOT NULL,
        correct_answer INTEGER CHECK(correct_answer BETWEEN 1 AND 4)
    )
    ''')

    easy_questions = [
        ('easy', 'What does CPU stand for?', 'Central Processing Unit',
         'Computer Processing Unit', 'Central Process Unit', 'Computer Personal Unit', 1),
        ('easy', 'Which of these is not a programming language?',
         'Python', 'HTML', 'Java', 'C++', 2),
        ('easy', 'What is the binary equivalent of decimal 5?',
         '101', '110', '100', '111', 1),
        ('easy', 'Which data structure uses FIFO (First In First Out) principle?',
         'Stack', 'Queue', 'Array', 'Tree', 2),
        ('easy', 'What does RAM stand for?', 'Random Access Memory',
         'Read Access Memory', 'Random Available Memory', 'Read Available Memory', 1),
        ('easy', 'Which of these is a relational database management system?',
         'MongoDB', 'SQLite', 'Redis', 'Cassandra', 2),
        ('easy', 'What is the time complexity of accessing an element in an array?',
         'O(1)', 'O(n)', 'O(log n)', 'O(n²)', 1),
        ('easy', 'Which language is known as the "mother of all languages"?',
         'C', 'Assembly', 'Fortran', 'COBOL', 1),
        ('easy', 'What does HTTP stand for?', 'HyperText Transfer Protocol',
         'HyperText Transmission Protocol', 'HighText Transfer Protocol', 'HighText Transmission Protocol', 1),
        ('easy', 'Which of these is not an operating system?',
         'Linux', 'Windows', 'macOS', 'Firefox', 4),
        ('easy', 'What is the extension of a Python file?',
         '.py', '.pt', '.pyt', '.python', 1),
        ('easy', 'Which symbol is used for single-line comments in Python?',
         '//', '#', '--', '/*', 2),
        ('easy', 'What does IDE stand for?', 'Integrated Development Environment', 'Integrated Design Environment',
         'Internal Development Environment', 'Interface Development Environment', 1),
        ('easy', 'Which data type is used to store true/false values?',
         'String', 'Integer', 'Boolean', 'Float', 3),
        ('easy', 'What is the output of 3 + 2 * 2 in Python?', '7', '10', '5', '9', 1),
        ('easy', 'Which protocol is used for secure communication over a network?',
         'HTTP', 'FTP', 'HTTPS', 'SMTP', 3),
        ('easy', 'What is the main purpose of an algorithm?', 'To solve a problem',
         'To create graphics', 'To design websites', 'To manage databases', 1),
        ('easy', 'Which of these is a loop structure in Python?',
         'repeat', 'for', 'cycle', 'iterate', 2),
        ('easy', 'What does SQL stand for?', 'Structured Query Language',
         'Simple Query Language', 'Standard Query Language', 'System Query Language', 1),
        ('easy', 'Which of these is a version control system?',
         'Git', 'Java', 'Eclipse', 'Node.js', 1),
        ('easy', 'What is the smallest unit of data in computing?',
         'Byte', 'Bit', 'Nibble', 'Word', 2),
        ('easy', 'Which of these is not a valid variable name in Python?',
         'my_var', '2var', '_var', 'var2', 2),
        ('easy', 'What does GUI stand for?', 'Graphical User Interface',
         'General User Interface', 'Graphical Unit Interface', 'General Unit Interface', 1),
        ('easy', 'Which operator is used for exponentiation in Python?',
         '^', '**', '^^', '*^', 2),
        ('easy',
         'What is the output of "hello"[1] in Python?', 'h', 'e', 'l', 'o', 2),
        ('easy', 'Which of these is not a Python data structure?',
         'List', 'Tuple', 'Dictionary', 'Class', 4),
        ('easy', 'What does OOP stand for?', 'Object-Oriented Programming',
         'Object-Option Programming', 'Object-Operator Programming', 'Object-Ordered Programming', 1),
        ('easy', 'Which function converts a string to lowercase in Python?',
         'lower()', 'toLower()', 'caseLower()', 'small()', 1),
        ('easy', 'What is the correct way to start a while loop in Python?',
         'while condition:', 'while (condition)', 'while {condition}', 'while condition do', 1),
        ('easy', 'Which of these is not a valid data type in Python?',
         'int', 'float', 'string', 'character', 4),
        ('easy', 'What is the correct syntax to import a module in Python?',
         'import module', 'include module', 'require module', 'using module', 1),
        ('easy', 'Which method adds an element to the end of a list in Python?',
         'append()', 'add()', 'insert()', 'push()', 1),
        ('easy', 'What does API stand for?', 'Application Programming Interface',
         'Application Process Interface', 'Automated Programming Interface', 'Automated Process Interface', 1),
        ('easy', 'Which of these is not a JavaScript framework?',
         'React', 'Angular', 'Django', 'Vue', 3),
        ('easy', 'What is the correct way to create a function in Python?',
         'def function():', 'function def():', 'function():', 'def function:', 1),
        ('easy', 'Which symbol is used for multiplication in Python?',
         'x', '*', '×', '.', 2),
        ('easy', 'What is the output of bool(0) in Python?',
         'True', 'False', '0', '1', 2),
        ('easy', 'Which of these is not a Python keyword?',
         'if', 'else', 'then', 'while', 3),
        ('easy', 'What is the correct way to comment multiple lines in Python?',
         '// comment //', '/* comment */', '# comment #', '""" comment """', 4),
        ('easy', 'Which function returns the length of a string in Python?',
         'count()', 'length()', 'len()', 'size()', 3),
        ('easy', 'What is the output of 10 / 3 in Python?',
         '3', '3.333...', '3.0', '3.00', 2),
        ('easy', 'Which of these is not a valid Python comparison operator?',
         '==', '!=', '=<', '>=', 3),
        ('easy', 'What is the correct way to create an empty list in Python?',
         'list()', '[]', 'list[]', 'Both A and B', 4),
        ('easy', 'Which method removes the last element from a list in Python?',
         'remove()', 'pop()', 'delete()', 'cut()', 2),
        ('easy', 'What does VPN stand for?', 'Virtual Private Network',
         'Virtual Public Network', 'Verified Private Network', 'Verified Public Network', 1),
        ('easy', 'Which of these is not a valid Python logical operator?',
         'and', 'or', 'not', 'xor', 4),
        ('easy', 'What is the output of "Hello" + "World" in Python?',
         'HelloWorld', 'Hello World', 'Hello+World', 'Error', 1),
        ('easy', 'Which function converts a string to an integer in Python?',
         'int()', 'strToInt()', 'parseInt()', 'toInt()', 1),
        ('easy', 'What is the correct way to check if a key exists in a Python dictionary?',
         'if key in dict:', 'if dict.has(key):', 'if dict.contains(key):', 'if dict[key] exists:', 1),
    ]

    medium_questions = [

        ('medium', 'What is the time complexity of merge sort?',
         'O(n)', 'O(n log n)', 'O(n²)', 'O(log n)', 2),
        ('medium', 'Which of these is not a NoSQL database?',
         'MongoDB', 'PostgreSQL', 'Cassandra', 'Redis', 2),
        ('medium', 'In object-oriented programming, what is it called when a class inherits from another class?',
         'Polymorphism', 'Encapsulation', 'Inheritance', 'Abstraction', 3),
        ('medium', 'What does DNS stand for?', 'Domain Name System',
         'Data Name System', 'Domain Network System', 'Data Network Service', 1),
        ('medium', 'Which sorting algorithm has the worst-case time complexity of O(n²)?',
         'Merge Sort', 'Quick Sort', 'Heap Sort', 'Bubble Sort', 4),
        ('medium', 'What is the maximum number of nodes in a binary tree of height h?',
         '2^h - 1', '2^h', 'h^2', '2^(h+1) - 1', 1),
        ('medium', 'Which protocol is used for sending email?',
         'HTTP', 'FTP', 'SMTP', 'SSH', 3),
        ('medium', 'What is the default port number for HTTP?',
         '80', '443', '21', '25', 1),
        ('medium', 'Which of these is not a design pattern?',
         'Singleton', 'Observer', 'Factory', 'Compiler', 4),
        ('medium', 'What does ACID stand for in database transactions?', 'Atomicity, Consistency, Isolation, Durability',
         'Accuracy, Consistency, Integrity, Durability', 'Atomicity, Consistency, Integrity, Durability', 'Atomicity, Correctness, Isolation, Durability', 1),
        ('medium', 'Which data structure is used for implementing recursion?',
         'Queue', 'Stack', 'Array', 'Linked List', 2),
        ('medium', 'What is the main advantage of using a linked list over an array?',
         'Faster access time', 'Easier to implement', 'Dynamic size', 'Better cache locality', 3),
        ('medium', 'Which of these is not a JavaScript framework?',
         'React', 'Angular', 'Django', 'Vue.js', 3),
        ('medium', 'What is the purpose of an index in a database?', 'To improve query performance',
         'To reduce storage space', 'To enforce data integrity', 'To create backups', 1),
        ('medium', 'Which algorithm is used for shortest path finding in a graph?',
         'Dijkstra\'s', 'Bubble Sort', 'Binary Search', 'Quick Sort', 1),
        ('medium', 'What is the time complexity of binary search?',
         'O(1)', 'O(log n)', 'O(n)', 'O(n log n)', 2),
        ('medium', 'Which of these is not a valid HTTP method?',
         'GET', 'POST', 'FETCH', 'DELETE', 3),
        ('medium', 'What is the main purpose of a foreign key in a database?', 'To ensure data uniqueness',
         'To create relationships between tables', 'To improve query performance', 'To encrypt data', 2),
        ('medium', 'Which of these is not a valid normalization form?',
         '1NF', '2NF', '3NF', '4GF', 4),
        ('medium', 'What is the main purpose of garbage collection?', 'To free memory',
         'To improve performance', 'To prevent memory leaks', 'All of the above', 4),
        ('medium', 'Which of these is not a valid Python decorator?',
         '@staticmethod', '@classmethod', '@property', '@function', 4),
        ('medium', 'What is the main purpose of the "yield" keyword in Python?',
         'To create a generator', 'To return a value', 'To pause execution', 'All of the above', 4),
        ('medium', 'Which of these is not a valid Python magic method?',
         '__init__', '__str__', '__len__', '__function__', 4),
        ('medium', 'What is the main purpose of the "with" statement in Python?',
         'To handle exceptions', 'To manage resources', 'To create loops', 'To define functions', 2),
        ('medium', 'Which of these is not a valid Python collection?',
         'Counter', 'DefaultDict', 'OrderedDict', 'SmartDict', 4),
        ('medium', 'What is the main purpose of the "lambda" function in Python?', 'To create anonymous functions',
         'To improve performance', 'To handle exceptions', 'To create decorators', 1),
        ('medium', 'Which of these is not a valid Python built-in exception?',
         'ValueError', 'TypeError', 'SyntaxError', 'CodeError', 4),
        ('medium', 'What is the main purpose of the "pass" statement in Python?',
         'To do nothing', 'To pass arguments', 'To pass control', 'To pass values', 1),
        ('medium', 'Which of these is not a valid Python string method?',
         'split()', 'join()', 'concat()', 'replace()', 3),
        ('medium', 'What is the main purpose of the "super()" function in Python?', 'To call parent class methods',
         'To create super variables', 'To improve performance', 'To handle exceptions', 1),
        ('medium', 'Which of these is not a valid Python comparison operator?',
         '==', '!=', '=<', '>=', 3),
        ('medium', 'What is the main purpose of the "zip()" function in Python?', 'To compress files',
         'To iterate over multiple sequences', 'To create dictionaries', 'To handle exceptions', 2),
        ('medium', 'Which of these is not a valid Python built-in function?',
         'map()', 'filter()', 'reduce()', 'collect()', 4),
        ('medium', 'What is the main purpose of the "enumerate()" function in Python?', 'To count elements',
         'To add indexes to iteration', 'To create dictionaries', 'To handle exceptions', 2),
        ('medium', 'Which of these is not a valid Python set operation?',
         'union()', 'intersection()', 'difference()', 'concatenate()', 4),
        ('medium', 'What is the main purpose of the "any()" function in Python?', 'To check if any element is true',
         'To check if all elements are true', 'To check if any element is false', 'To check if all elements are false', 1),
        ('medium', 'Which of these is not a valid Python dictionary method?',
         'keys()', 'values()', 'items()', 'elements()', 4),
        ('medium', 'What is the main purpose of the "globals()" function in Python?', 'To get global variables',
         'To set global variables', 'To delete global variables', 'All of the above', 1),
        ('medium', 'Which of these is not a valid Python file mode?',
         'r', 'w', 'a', 'z', 4),
        ('medium', 'What is the main purpose of the "isinstance()" function in Python?', 'To check object type',
         'To check class inheritance', 'To check object attributes', 'To check object methods', 1),
        ('medium', 'Which of these is not a valid Python number type?',
         'int', 'float', 'complex', 'decimal', 4),
        ('medium', 'What is the main purpose of the "repr()" function in Python?',
         'To get object representation', 'To get object string', 'To get object type', 'To get object value', 1),
        ('medium', 'Which of these is not a valid Python built-in constant?',
         'True', 'False', 'None', 'Null', 4),
        ('medium', 'What is the main purpose of the "locals()" function in Python?', 'To get local variables',
         'To set local variables', 'To delete local variables', 'All of the above', 1),
        ('medium', 'Which of these is not a valid Python operator precedence?',
         '**', '*/', '+-', '><', 4),
        ('medium', 'What is the main purpose of the "dir()" function in Python?', 'To get object attributes',
         'To get object methods', 'To get object properties', 'All of the above', 4),
        ('medium', 'Which of these is not a valid Python built-in module?',
         'os', 'sys', 'math', 'calc', 4),
        ('medium', 'What is the main purpose of the "help()" function in Python?',
         'To get help', 'To get documentation', 'To get examples', 'All of the above', 4),
        ('medium', 'Which of these is not a valid Python built-in exception?',
         'IndexError', 'KeyError', 'ValueError', 'CodeError', 4),
        ('medium', 'What is the main purpose of the "break" statement in Python?',
         'To exit loops', 'To skip iterations', 'To handle exceptions', 'To return values', 1),
        ('medium', 'Which of these is not a valid Python built-in function?',
         'abs()', 'round()', 'ceil()', 'floor()', 3),

    ]

    difficult_questions = [

        ('difficult', 'What is the time complexity of the Knuth-Morris-Pratt algorithm?',
         'O(n)', 'O(n log n)', 'O(n + m)', 'O(n²)', 3),
        ('difficult', 'In the CAP theorem, what does "CAP" stand for?', 'Consistency, Availability, Partition tolerance',
         'Correctness, Availability, Performance', 'Consistency, Accuracy, Partition tolerance', 'Correctness, Accuracy, Performance', 1),
        ('difficult', 'Which of these is not a NP-complete problem?', 'Traveling Salesman',
         'Boolean Satisfiability', 'Knapsack', 'Linear Programming', 4),
        ('difficult', 'What is the main principle behind public-key cryptography?',
         'Symmetric encryption', 'One-way functions', 'Trapdoor functions', 'Both B and C', 4),
        ('difficult', 'Which algorithm is used for page replacement in operating systems?',
         'LRU', 'FIFO', 'Both A and B', 'Neither A nor B', 3),
        ('difficult', 'What is the halting problem?', 'Determining if a program will finish running',
         'Determining program speed', 'Determining program memory usage', 'Determining program correctness', 1),
        ('difficult', 'Which of these is not a type of machine learning?', 'Supervised learning',
         'Unsupervised learning', 'Reinforcement learning', 'Compiler learning', 4),
        ('difficult', 'What is the time complexity of matrix multiplication using Strassen\'s algorithm?',
         'O(n²)', 'O(n^3)', 'O(n^2.807)', 'O(n log n)', 3),
        ('difficult', 'Which of these is not a normalization form in databases?',
         '1NF', '2NF', '3NF', '4GF', 4),
        ('difficult', 'What does BFS stand for in graph algorithms?', 'Best First Search',
         'Breadth First Search', 'Binary First Search', 'Bidirectional First Search', 2),
        ('difficult', 'Which theorem states that no consistent system of axioms can prove all truths about arithmetic?',
         'Church-Turing thesis', 'Gödel\'s incompleteness theorem', 'P vs NP problem', 'Halting theorem', 2),
        ('difficult', 'What is the main challenge in implementing blockchain?',
         'Data storage', 'Consensus mechanism', 'User interface', 'Compiler optimization', 2),
        ('difficult', 'Which of these is not a type of SQL injection?',
         'Union-based', 'Boolean-based', 'Time-based', 'Loop-based', 4),
        ('difficult', 'What is the main advantage of quantum computing over classical computing?', 'Faster clock speed',
         'Ability to solve certain problems exponentially faster', 'Lower power consumption', 'Easier programming', 2),
        ('difficult', 'Which architecture style is used by REST APIs?',
         'Client-server', 'Peer-to-peer', 'Monolithic', 'Microkernel', 1),
        ('difficult', 'What is the time complexity of the A* search algorithm?',
         'O(b^d)', 'O(d^b)', 'O(bd)', 'O(b + d)', 1),
        ('difficult', 'Which of these is not a concurrency control technique in databases?',
         'Locking', 'Timestamp ordering', 'Optimistic concurrency control', 'Hashing', 4),
        ('difficult', 'What is the main principle behind the MapReduce programming model?',
         'Divide and conquer', 'Shared memory', 'Message passing', 'Data parallelism', 4),
        ('difficult', 'Which of these is not a valid deadlock prevention technique?',
         'Resource ordering', 'Hold and wait', 'Preemption', 'Circular wait', 2),
        ('difficult', 'What is the main purpose of the Paxos algorithm?',
         'Distributed consensus', 'Load balancing', 'Data partitioning', 'Fault tolerance', 1),
        ('difficult', 'Which of these is not a valid cache replacement policy?',
         'LRU', 'FIFO', 'MRU', 'LRA', 4),
        ('difficult', 'What is the main principle behind content-addressable storage?', 'Data is accessed by content hash',
         'Data is accessed by location', 'Data is accessed by name', 'Data is accessed by size', 1),
        ('difficult', 'Which of these is not a valid distributed system architecture?',
         'Client-server', 'Peer-to-peer', 'Three-tier', 'Single-tier', 4),
        ('difficult', 'What is the main purpose of the Byzantine Generals Problem?', 'To illustrate distributed consensus challenges',
         'To demonstrate encryption techniques', 'To show load balancing issues', 'To explain caching strategies', 1),
        ('difficult', 'Which of these is not a valid virtualization technique?', 'Full virtualization',
         'Para-virtualization', 'Hardware-assisted virtualization', 'Software virtualization', 4),
        ('difficult', 'What is the main principle behind the Actor model of concurrency?',
         'Shared memory', 'Message passing', 'Data parallelism', 'Task parallelism', 2),
        ('difficult', 'Which of these is not a valid cloud computing service model?',
         'IaaS', 'PaaS', 'SaaS', 'DaaS', 4),
        ('difficult', 'What is the main purpose of the Raft consensus algorithm?',
         'Distributed consensus', 'Load balancing', 'Data partitioning', 'Fault tolerance', 1),
        ('difficult', 'Which of these is not a valid NoSQL database type?',
         'Document', 'Key-value', 'Column-family', 'Table', 4),
        ('difficult', 'What is the main principle behind eventual consistency?', 'All nodes see same data at same time',
         'All nodes will eventually see same data', 'Data is always consistent', 'Data is never consistent', 2),
        ('difficult', 'Which of these is not a valid distributed computing pattern?',
         'MapReduce', 'Publish-subscribe', 'Request-reply', 'Compile-execute', 4),
        ('difficult', 'What is the main purpose of the Two-Phase Commit protocol?',
         'Distributed transaction atomicity', 'Data replication', 'Load balancing', 'Fault tolerance', 1),
        ('difficult', 'Which of these is not a valid microservices communication pattern?',
         'Synchronous HTTP', 'Asynchronous messaging', 'Event-driven', 'Direct memory access', 4),
        ('difficult', 'What is the main principle behind sharding in databases?',
         'Horizontal partitioning', 'Vertical partitioning', 'Data replication', 'Data compression', 1),
        ('difficult', 'Which of these is not a valid distributed system consistency model?',
         'Strong', 'Eventual', 'Causal', 'Parallel', 4),
        ('difficult', 'What is the main purpose of the Chubby lock service?',
         'Distributed locking', 'Data storage', 'Load balancing', 'Fault tolerance', 1),
        ('difficult', 'Which of these is not a valid distributed file system?',
         'HDFS', 'GFS', 'NFS', 'DFS', 4),
        ('difficult', 'What is the main principle behind the BASE database model?', 'Basically Available, Soft state, Eventual consistency',
         'Basic Atomicity, Soft state, Eventual consistency', 'Basically Available, Strong consistency, Eventual consistency', 'Basic Atomicity, Strong consistency, Eventual consistency', 1),
        ('difficult', 'Which of these is not a valid distributed computing challenge?',
         'Latency', 'Bandwidth', 'Clock synchronization', 'Compiler optimization', 4),
        ('difficult', 'What is the main purpose of the ZooKeeper service?',
         'Distributed coordination', 'Data storage', 'Load balancing', 'Fault tolerance', 1),
        ('difficult', 'Which of these is not a valid distributed system failure mode?',
         'Crash failure', 'Omission failure', 'Timing failure', 'Syntax failure', 4),
        ('difficult', 'What is the main principle behind the Lambda architecture?',
         'Batch and stream processing', 'Data replication', 'Load balancing', 'Fault tolerance', 1),
        ('difficult', 'Which of these is not a valid distributed transaction protocol?',
         'Two-Phase Commit', 'Three-Phase Commit', 'Paxos Commit', 'Saga', 3),
        ('difficult', 'What is the main purpose of the Gossip protocol?',
         'Distributed information dissemination', 'Data storage', 'Load balancing', 'Fault tolerance', 1),
        ('difficult', 'Which of these is not a valid distributed system design pattern?',
         'Bulkhead', 'Circuit Breaker', 'Retry', 'Compiler', 4),
        ('difficult', 'What is the main principle behind the CQRS pattern?', 'Command-Query Responsibility Segregation',
         'Command-Query Replication Segregation', 'Command-Query Resource Segregation', 'Command-Query Response Segregation', 1),
        ('difficult', 'Which of these is not a valid distributed tracing system?',
         'Zipkin', 'Jaeger', 'OpenTelemetry', 'OpenTrace', 4),
        ('difficult', 'What is the main purpose of the Sidecar pattern?',
         'To provide helper services', 'To store data', 'To balance load', 'To handle faults', 1),
        ('difficult', 'Which of these is not a valid distributed system metric?',
         'Latency', 'Throughput', 'Error rate', 'Code coverage', 4),
        ('difficult', 'What is the main principle behind the Event Sourcing pattern?', 'State changes are stored as sequence of events',
         'Events are stored as sequence of states', 'State changes are compressed', 'Events are compressed', 1),
        ('difficult', 'Which of these is not a valid distributed system testing technique?',
         'Chaos engineering', 'Property-based testing', 'Unit testing', 'Compiler testing', 4),
        ('difficult', 'What is the main purpose of the Bulkhead pattern?',
         'To isolate failures', 'To store data', 'To balance load', 'To handle faults', 1),
        ('difficult', 'Which of these is not a valid distributed system deployment strategy?',
         'Blue-green', 'Canary', 'Rolling', 'Compiler', 4),
        ('difficult', 'What is the main principle behind the Circuit Breaker pattern?',
         'To prevent cascading failures', 'To store data', 'To balance load', 'To handle faults', 1),

    ]

    all_questions = easy_questions + medium_questions + difficult_questions

    cursor.executemany('''
    INSERT INTO questions (difficulty, question_text, option1, option2, option3, option4, correct_answer)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', all_questions)

    # Commit and close
    conn.commit()
    conn.close()
    print("Database 'general_sports_quiz.db' created successfully with 150 general questions!")


if __name__ == '__main__':
    create_database()
