import sqlite3


def create_database():

    conn = sqlite3.connect('general_knowledge_quiz.db')
    cursor = conn.cursor()

    cursor.execute('DROP TABLE IF EXISTS questions')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS questions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        difficulty TEXT CHECK(difficulty IN ('easy', 'medium', 'difficult')),
        question_text TEXT NOT NULL,
        option1 TEXT NOT NULL,
        option2 TEXT NOT NULL,
        option3 TEXT NOT NULL,
        option4 TEXT NOT NULL,
        correct_answer INTEGER CHECK(correct_answer BETWEEN 1 AND 4)
    )
    ''')

    easy_questions = [
        ('easy', "What is the capital of France?",
         "London", "Paris", "Rome", "Berlin", 2),
        ('easy', "What is the highest mountain in the world?",
         "K2", "Kangchenjunga", "Mount Everest", "Lhotse", 3),
        ('easy', "What is the chemical symbol for water?", "Wo", "Wa", "H2O", "HO2", 3),
        ('easy', "Who painted the Mona Lisa?", "Vincent van Gogh",
         "Leonardo da Vinci", "Pablo Picasso", "Claude Monet", 2),
        ('easy', "What is the largest planet in our solar system?",
         "Mars", "Earth", "Jupiter", "Saturn", 3),
        ('easy', "What is the currency of Japan?",
         "Yuan", "Won", "Yen", "Ringgit", 3),
        ('easy', "What is the name of the first man to walk on the moon?",
         "Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Alan Shepard", 2),
        ('easy', "What is the smallest country in the world?",
         "Maldives", "Vatican City", "Monaco", "San Marino", 2),
        ('easy', "What is the chemical symbol for gold?", "Au", "Ag", "Fe", "Cu", 1),
        ('easy', "What is the tallest animal in the world?",
         "Elephant", "Lion", "Giraffe", "Bear", 3),
        ('easy', "Which planet is known as the 'Red Planet'?",
         "Venus", "Mars", "Jupiter", "Saturn", 2),
        ('easy', "What is the largest ocean on Earth?", "Atlantic Ocean",
         "Indian Ocean", "Arctic Ocean", "Pacific Ocean", 4),
        ('easy', "Who wrote 'Romeo and Juliet'?", "Charles Dickens",
         "William Shakespeare", "Jane Austen", "Mark Twain", 2),
        ('easy', "What is the human body's largest organ?",
         "Heart", "Liver", "Skin", "Brain", 3),
        ('easy', "What is the primary gas that plants absorb from the atmosphere?",
         "Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen", 2),
        ('easy', "What is the name of the famous clock tower in London?",
         "Big Ben", "Eiffel Tower", "Tower of London", "Westminster Abbey", 1),
        ('easy', "Which animal is known as the 'King of the Jungle'?",
         "Tiger", "Elephant", "Lion", "Cheetah", 3),
        ('easy', "What is the name of the force that pulls objects towards the Earth?",
         "Magnetism", "Gravity", "Friction", "Electricity", 2),
        ('easy', "What is the shape of the Earth?",
         "Flat", "Square", "Round", "Triangular", 3),
        ('easy', "What is the name of our galaxy?", "Andromeda",
         "Milky Way", "Triangulum", "Whirlpool", 2),
        ('easy', "What is the name of the first month of the year?",
         "February", "January", "December", "March", 2),
        ('easy', "How many days are in a leap year?", "365", "366", "367", "364", 2),
        ('easy', "What colors are the stars of the American flag?", "Red, White, and Blue",
         "Red, Yellow, and Blue", "Green, White, and Blue", "Black, White, and Blue", 1),
        ('easy', "What is the name of the largest bird in the world?",
         "Eagle", "Penguin", "Ostrich", "Albatross", 3),
        ('easy', "What is the name of the tallest building in the world?",
         "Shanghai Tower", "Burj Khalifa", "Abraj Al-Bait", "Ping An Finance Centre", 2),
        ('easy', "What is the name of the world's longest river?",
         "Yellow River", "Amazon River", "Yangtze River", "Nile River", 4),
        ('easy', "What is the name of the first man to set foot in space?",
         "Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Alan Shepard", 3),
        ('easy', "What is the name of the fairy tale written by Hans Christian Andersen about a girl who lived under the sea?",
         "Cinderella", "Snow White", "The Little Mermaid", "Sleeping Beauty", 3),
        ('easy', "What is the title of the first book of The Chronicles of Narnia by C.S. Lewis?",
         "The Lion, the Witch, and the Wardrobe", "Prince Caspian", "The Voyage of the Dawn Treader", "The Silver Chair", 1),
        ('easy', "What is the name of the group of people who designed and built the first computers?",
         "The Bletchley Park team", "The Google team", "The Apple team", "The Microsoft team", 1),
        ('easy', "What is the river that flows through Egypt?",
         "Tigris", "Euphrates", "Nile", "Amazon", 3),
        ('easy', "What is the name of the sea between Great Britain and France?",
         "Irish Sea", "North Sea", "English Channel", "Baltic Sea", 3),
        ('easy', "What is the name of the first book of the Harry Potter series by J.K. Rowling?", "Harry Potter and the Chamber of Secrets",
         "Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Sorcerer's Stone", "Harry Potter and the Goblet of Fire", 3),
        ('easy', "What is the name of the group that wrote and sang the song 'Bohemian Rhapsody'?",
         "The Beatles", "Queen", "The Rolling Stones", "Pink Floyd", 2),
        ('easy', "What is the name of the first animated movie released by Disney?",
         "Snow White and the Seven Dwarfs", "Pinocchio", "Fantasia", "Dumbo", 1),
        ('easy', "What is the name of the device used to measure earthquakes?",
         "Barometer", "Hygrometer", "Seismograph", "Anemometer", 3),
        ('easy', "What is the name of the first animal successfully cloned?",
         "Dog", "Sheep", "Cat", "Mouse", 2),
        ('easy', "What is the name of the first search engine?",
         "Yahoo", "Google", "Archie", "Bing", 3),
        ('easy', "What is the name of the first social media website?",
         "Facebook", "Twitter", "Myspace", "Friendster", 4),
        ('easy', "What is the name of the first smartphone?",
         "BlackBerry Storm", "iPhone", "HTC Dream", "Nokia N97", 2),
        ('easy', "What is the name of the first video game?",
         "Pong", "Space Invaders", "Pac-Man", "Donkey Kong", 1),
        ('easy', "What is the name of the first personal computer?",
         "IBM PC", "Apple II", "Commodore 64", "Altair 8800", 4),
        ('easy', "What is the name of the first web browser?",
         "Netscape Navigator", "Internet Explorer", "Mosaic", "Safari", 3),
        ('easy', "What is the name of the first email service?",
         "Hotmail", "Gmail", "Yahoo Mail", "AOL Mail", 1),
        ('easy', "What is the name of the first online marketplace?",
         "Amazon", "eBay", "Alibaba", "Shopify", 1),
        ('easy', "What is the name of the first online encyclopedia?",
         "Wikipedia", "Britannica", "Encarta", "WorldBook", 1),
        ('easy', "What is the name of the first streaming service?",
         "Netflix", "Hulu", "Amazon Prime Video", "Disney+", 1),
        ('easy', "What is the name of the first cryptocurrency?",
         "Ethereum", "Ripple", "Bitcoin", "Litecoin", 3),
        ('easy', "What is the name of the first self-driving car?",
         "Waymo", "Tesla Autopilot", "GM Cruise", "Mobileye", 1),
        ('easy', "What is the name of the first virtual reality headset?",
         "Oculus Rift", "HTC Vive", "PlayStation VR", "Samsung Gear VR", 1),
    ]

    # Medium General Knowledge Questions
    medium_questions = [
        ('medium', "What is the chemical composition of ozone?",
         "O2", "O3", "CH4", "CO2", 2),
        ('medium', "Which planet is known as the 'Morning Star' or 'Evening Star'?",
         "Mars", "Venus", "Jupiter", "Saturn", 2),
        ('medium', "What is the name of the galaxy closest to the Milky Way?", "Triangulum Galaxy",
         "Andromeda Galaxy", "Large Magellanic Cloud", "Small Magellanic Cloud", 2),
        ('medium', "What is the largest known volcano in our solar system?",
         "Mauna Loa", "Mount Etna", "Olympus Mons", "Mount Vesuvius", 3),
        ('medium', "What is the name of the supercontinent that existed about 300 million years ago?",
         "Gondwana", "Laurasia", "Pangea", "Rodinia", 3),
        ('medium', "What is the name of the world's deepest ocean trench?", "Mariana Trench",
         "Puerto Rico Trench", "Java Trench", "Kurile-Kamchatka Trench", 1),
        ('medium', "Which gas is most abundant in Earth's atmosphere?",
         "Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen", 3),
        ('medium', "What is the name of the phenomenon where the Earth's magnetic field deflects solar wind?",
         "Aurora Borealis", "Van Allen Belts", "Magnetosphere", "Ionosphere", 3),
        ('medium', "What is the name of the process by which plants convert sunlight into chemical energy?",
         "Respiration", "Photosynthesis", "Transpiration", "Fermentation", 2),
        ('medium', "What is the name of the theory that explains the origin of the universe?",
         "Steady State Theory", "Big Bang Theory", "Inflationary Theory", "Oscillating Universe Theory", 2),
        ('medium', "What is the name of the first cloned mammal?",
         "Polly", "Dolly", "Celia", "Emma", 2),
        ('medium', "What is the name of the first artificial satellite launched into space?",
         "Explorer 1", "Sputnik 1", "Vanguard 1", "Cosmos 1", 2),
        ('medium', "What is the name of the first human to travel to space?",
         "Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Alan Shepard", 3),
        ('medium', "What is the name of the first successful vaccine?", "Polio Vaccine",
         "Smallpox Vaccine", "Measles Vaccine", "Influenza Vaccine", 2),
        ('medium', "What is the name of the first antibiotic discovered?",
         "Penicillin", "Streptomycin", "Tetracycline", "Erythromycin", 1),
        ('medium', "What is the name of the first computer programmer?",
         "Ada Lovelace", "Alan Turing", "John von Neumann", "Grace Hopper", 1),
        ('medium', "What is the name of the first programmable electronic computer?",
         "ENIAC", "Colossus", "Z3", "ABC", 1),
        ('medium', "What is the name of the first high-level programming language?",
         "Fortran", "COBOL", "ALGOL", "BASIC", 1),
        ('medium', "What is the name of the first operating system?",
         "MS-DOS", "UNIX", "CP/M", "macOS", 2),
        ('medium', "What is the name of the first graphical user interface (GUI)?",
         "Windows", "macOS", "Xerox Alto", "Linux", 3),
        ('medium', "What is the name of the first commercial jet airliner?",
         "Boeing 707", "De Havilland Comet", "Douglas DC-8", "Airbus A300", 1),
        ('medium', "What is the name of the first supersonic passenger airliner?",
         "Boeing 2707", "Tupolev Tu-144", "Concorde", "Lockheed L-2000", 3),
        ('medium', "What is the name of the first space shuttle?",
         "Enterprise", "Columbia", "Challenger", "Discovery", 1),
        ('medium', "What is the name of the first space station?",
         "Salyut 1", "Skylab", "Mir", "International Space Station", 1),
        ('medium', "What is the name of the first reusable rocket?",
         "Saturn V", "Space Shuttle", "Falcon 1", "Ariane 5", 2),
        ('medium', "What is the name of the first artificial heart?",
         "Jarvik 7", "AbioCor", "SynCardia TAH", "Carmat TAH", 1),
        ('medium', "What is the name of the first genetically engineered food?",
         "Flavr Savr Tomato", "Golden Rice", "Bt Corn", "AquAdvantage Salmon", 1),
        ('medium', "What is the name of the first successful organ transplant?",
         "Kidney Transplant", "Liver Transplant", "Heart Transplant", "Lung Transplant", 1),
        ('medium', "What is the name of the first bionic eye implant?",
         "Argus I", "Argus II", "Retina Implant AG", "Alpha IMS", 1),
        ('medium', "What is the name of the first 3D-printed organ?",
         "Kidney", "Liver", "Heart", "Bladder", 4),
        ('medium', "What is the name of the first country to legalize same-sex marriage?",
         "Netherlands", "Belgium", "Canada", "Spain", 1),
        ('medium', "What is the name of the first woman to travel to space?",
         "Valentina Tereshkova", "Sally Ride", "Svetlana Savitskaya", "Judith Resnik", 1),
        ('medium', "What is the name of the first film to win the Academy Award for Best Picture?",
         "Wings", "Sunrise", "The Broadway Melody", "All Quiet on the Western Front", 1),
        ('medium', "What is the name of the first book printed on the Gutenberg press?",
         "The Canterbury Tales", "The Bible", "Don Quixote", "Divine Comedy", 2),
        ('medium', "What is the name of the first painting sold on canvas?",
         "The Starry Night", "Mona Lisa", "The Birth of Venus", "The Scream", 3),
        ('medium', "What is the name of the first photograph?", "View from the Window at Le Gras",
         "Boulevard du Temple", "The Horse in Motion", "The Pencil of Nature", 1),
        ('medium', "What is the name of the first recorded song?", "Au clair de la lune",
         "God Save the Queen", "La Marseillaise", "Yankee Doodle", 1),
        ('medium', "What is the name of the first radio broadcast?", "Reginald Fessenden's broadcast",
         "Lee de Forest's broadcast", "Guglielmo Marconi's broadcast", "David Sarnoff's broadcast", 1),
        ('medium', "What is the name of the first television broadcast?", "John Logie Baird's broadcast",
         "Philo Farnsworth's broadcast", "Vladimir Zworykin's broadcast", "Charles Jenkins' broadcast", 1),
        ('medium', "What is the name of the first animated television series?",
         "Crusader Rabbit", "The Flintstones", "The Jetsons", "Rocky and His Friends", 1),
        ('medium', "What is the name of the first music video to air on MTV?",
         "Video Killed the Radio Star", "Bohemian Rhapsody", "Thriller", "Like a Virgin", 1),
        ('medium', "What is the name of the first computer-animated film?",
         "Toy Story", "A Bug's Life", "Shrek", "Finding Nemo", 1),
        ('medium', "What is the name of the first live-action film to use CGI?",
         "Tron", "Terminator 2: Judgment Day", "Jurassic Park", "Forrest Gump", 1),
        ('medium', "What is the name of the first film released in IMAX?",
         "Tiger Child", "North of Superior", "Ocean", "Polar Life", 1),
        ('medium', "What is the name of the first film released in 3D?",
         "Bwana Devil", "House of Wax", "Kiss Me, Kate", "Dial M for Murder", 1),
        ('medium', "What is the name of the first film to use Dolby Stereo?",
         "Star Wars", "Apocalypse Now", "Alien", "Superman", 1),
        ('medium', "What is the name of the first film to be digitally projected?",
         "Star Wars: Episode I – The Phantom Menace", "Toy Story 2", "Fight Club", "The Matrix", 1),
        ('medium', "What is the name of the first film to be shot entirely on an iPhone?",
         "Tangerine", "Unsane", "High Flying Bird", "Searching", 1),
        ('medium', "What is the name of the first film to win an Oscar for Best Foreign Language Film?",
         "The Bicycle Thieves", "Rashomon", "La Strada", "Black Orpheus", 1),
    ]

    difficult_questions = [
        ('difficult', "What is the name of the theoretical particle that travels faster than light?",
         "Tachyon", "Neutrino", "Graviton", "WIMP", 1),
        ('difficult', "What is the name of the mathematical concept that describes a shape that is infinitely complex?",
         "Fractal", "Topology", "Calculus", "Geometry", 1),
        ('difficult', "What is the name of the quantum phenomenon where two particles become linked and share the same fate?",
         "Superposition", "Entanglement", "Quantum Tunneling", "Quantum Decoherence", 2),
        ('difficult', "What is the name of the scientific principle that states that it is impossible to know both the position and momentum of a particle?",
         "Heisenberg Uncertainty Principle", "Pauli Exclusion Principle", "Hund's Rule", "Schrödinger's Equation", 1),
        ('difficult', "What is the name of the cosmological model that proposes that the universe is expanding at an accelerating rate?",
         "Steady State Model", "Big Bang Model", "Lambda-CDM Model", "Oscillating Universe Model", 3),
        ('difficult', "What is the name of the geological epoch that began about 2.6 million years ago and is characterized by cycles of glaciation?",
         "Holocene", "Pleistocene", "Pliocene", "Miocene", 2),
        ('difficult', "What is the name of the deepest point in Earth's crust?",
         "Mariana Trench", "Challenger Deep", "Sirena Deep", "Hadal Zone", 2),
        ('difficult', "What is the name of the largest known prime number?",
         "Mersenne Prime", "Fermat Prime", "Gaussian Prime", "Sophie Germain Prime", 1),
        ('difficult', "What is the name of the mathematical problem that has remained unsolved for over 150 years and offers a million-dollar prize?",
         "Riemann Hypothesis", "P versus NP problem", "Yang–Mills existence and mass gap", "Navier–Stokes existence and smoothness", 1),
        ('difficult', "What is the name of the philosophical concept that questions the nature of reality and knowledge?",
         "Solipsism", "Nihilism", "Existentialism", "Epistemology", 4),
        ('difficult', "What is the name of the first synthetic polymer?",
         "Nylon", "Bakelite", "PVC", "Polystyrene", 2),
        ('difficult', "What is the name of the first genetically modified animal approved for human consumption?",
         "EnviroPig", "AquaAdvantage Salmon", "Bt Cow", "Fast-Growing Chicken", 2),
        ('difficult', "What is the name of the first human genome to be fully sequenced?",
         "Human Genome Project", "Celera Genomics", "International HapMap Project", "1000 Genomes Project", 1),
        ('difficult', "What is the name of the first drug designed using computer-aided drug design?",
         "Captopril", "Zidovudine (AZT)", "Saquinavir", "Imatinib", 1),
        ('difficult', "What is the name of the first vaccine against a human cancer?",
         "Hepatitis B Vaccine", "HPV Vaccine", "Cervarix", "Gardasil", 2),
        ('difficult', "What is the name of the first artificial organ to be successfully implanted in a human?",
         "Artificial Heart", "Artificial Kidney", "Artificial Liver", "Artificial Lung", 1),
        ('difficult', "What is the name of the first exoplanet discovered around a Sun-like star?",
         "51 Pegasi b", "HD 209458 b", "Gliese 581g", "Kepler-186f", 1),
        ('difficult', "What is the name of the first image of a black hole?",
         "Sagittarius A*", "M87*", "Powehi", "Cygnus X-1", 2),
        ('difficult', "What is the name of the first gravitational wave detected?",
         "GW150914", "GW151226", "GW170104", "GW170817", 1),
        ('difficult', "What is the name of the first life form created in a laboratory?",
         "Mycoplasma laboratorium", "E. coli O157:H7", "Salmonella typhimurium", "Staphylococcus aureus", 1),
        ('difficult', "What is the name of the first piece of music written for more than 40 voices?",
         "Spem in alium", "Missa Solemnis", "The Creation", "Vespro della Beata Vergine", 1),
        ('difficult', "What is the name of the first novel written in English?",
         "Beowulf", "The Canterbury Tales", "Pamela", "The Pilgrim's Progress", 3),
        ('difficult', "What is the name of the first play written by William Shakespeare?",
         "Henry VI, Part 1", "Richard III", "Titus Andronicus", "The Comedy of Errors", 1),
        ('difficult', "What is the name of the first opera?",
         "Dafne", "Euridice", "Orfeo", "Poppea", 1),
        ('difficult', "What is the name of the first ballet?",
         "Le Ballet Comique de la Reine", "La Sylphide", "Giselle", "Swan Lake", 1),
        ('difficult', "What is the name of the first film directed by a woman?",
         "Meshes of the Afternoon", "Suspense", "The Kid", "Cleopatra", 2),
        ('difficult', "What is the name of the first animated film directed by a woman?",
         "The Adventures of Prince Achmed", "Snow White and the Seven Dwarfs", "Fantasia", "Persepolis", 1),
        ('difficult', "What is the name of the first television show created by a woman?",
         "I Love Lucy", "The Mary Tyler Moore Show", "One Day at a Time", "Designing Women", 1),
        ('difficult', "What is the name of the first video game designed by a woman?",
         "Pac-Man", "Donkey Kong", "Ms. Pac-Man", "Centipede", 3),
        ('difficult', "What is the name of the first work of art sold as an NFT?",
         "Everydays: The First 5000 Days", "CryptoPunks", "Bored Ape Yacht Club", "Hashmasks", 1),
        ('difficult', "What is the name of the first country to grant women the right to vote?",
         "New Zealand", "Australia", "United States", "United Kingdom", 1),
        ('difficult', "What is the name of the first person to undergo a successful gene editing procedure inside the body?",
         "Victoria Gray", "Jennifer Doudna", "Emmanuelle Charpentier", "Feng Zhang", 1),
        ('difficult', "What is the name of the first animal to be successfully cloned from frozen tissue?",
         "Dolly", "Snuppy", "Cumulina", "Mable", 4),
        ('difficult', "What is the name of the first plant grown entirely in space?",
         "Arabidopsis thaliana", "Oryza sativa", "Triticum aestivum", "Solanum tuberosum", 1),
        ('difficult', "What is the name of the first artificial intelligence to pass the Turing test?",
         "ELIZA", "ALICE", "Eugene Goostman", "Cleverbot", 3),
        ('difficult', "What is the name of the first robot to gain citizenship?",
         "Sophia", "ASIMO", "Pepper", "Atlas", 1),
        ('difficult', "What is the name of the first building to be 3D-printed?",
         "Office of the Future", "Dubai Future Academy", "Winsun apartments", "Museum of the Future", 1),
        ('difficult', "What is the name of the first artwork sent into space?",
         "The Golden Record", "Cosmic Dancer", "Messages to Earth", "Across the Universe", 1),
        ('difficult', "What is the name of the first book published online?",
         "Riding the Bullet", "The Gutenberg Bible", "Project Gutenberg", "Eastgate Systems", 1),
        ('difficult', "What is the name of the first film released on the internet?",
         "Happy Days", "George Lucas in Love", "The Spirit of Christmas", "Trouble", 2),
        ('difficult', "What is the name of the first song performed in space?",
         "Space Oddity", "Across the Universe", "Gravity", "Rocket Man", 2),
        ('difficult', "What is the name of the first tweet ever sent?",
         "just setting up my twttr", "Hello Twitter!", "My first tweet", "This is Twitter", 1),
        ('difficult', "What is the name of the first emoji ever created?",
         ":)", ":-)", ":D", "<3", 2),
        ('difficult', "What is the name of the first meme?", "Dancing Baby",
         "Hamster Dance", "Oogachaka Baby", "All your base are belong to us", 1),
    ]

    all_questions = easy_questions + medium_questions + difficult_questions

    cursor.executemany('''
    INSERT INTO questions (difficulty, question_text, option1, option2, option3, option4, correct_answer)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', all_questions)

    conn.commit()
    conn.close()
    print("Database 'general_knowledge_quiz.db' created successfully with 150 general questions!")


if __name__ == '__main__':
    create_database()
