import sqlite3


def create_database():

    conn = sqlite3.connect('geography_quiz.db')
    cursor = conn.cursor()

    # Drop table if it exists (optional)
    cursor.execute('DROP TABLE IF EXISTS questions')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS questions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        difficulty TEXT CHECK(difficulty IN ('easy', 'medium', 'difficult')),
        question_text TEXT NOT NULL,
        option1 TEXT NOT NULL,
        option2 TEXT NOT NULL,
        option3 TEXT NOT NULL,
        option4 TEXT NOT NULL,
        correct_answer INTEGER CHECK(correct_answer BETWEEN 1 AND 4)
    )
    ''')

    # Example list of questions – You need to expand each difficulty to 50 questions
    # Below only partial data is shown for illustration
    easy_questions = [
        ('easy', 'Mount Everest is located in which mountain range?',
         'Andes', 'Alps', 'Himalayas', 'Rockies', 3),
        ('easy', 'Which country is both a continent and an island?',
         'New Zealand', 'Australia', 'Iceland', 'Madagascar', 2),
        ('easy', 'The Sahara Desert is primarily located in which continent?',
         'Asia', 'Africa', 'South America', 'Australia', 2),
        ('easy', 'Which river is the longest in the world?',
         'Amazon', 'Nile', 'Yangtze', 'Mississippi', 2),
        ('easy', 'What is the capital of Japan?',
         'Seoul', 'Beijing', 'Tokyo', 'Bangkok', 3),
        ('easy', 'Which of these countries is not in Europe?',
         'Portugal', 'Hungary', 'Morocco', 'Sweden', 3),
        ('easy', 'The Great Barrier Reef is off the coast of which country?',
         'Brazil', 'Australia', 'Indonesia', 'Mexico', 2),
        ('easy', 'Which continent contains the most countries?',
         'Asia', 'Africa', 'Europe', 'North America', 2),
        ('easy', 'What is the capital of Canada?',
         'Toronto', 'Ottawa', 'Montreal', 'Vancouver', 2),
        ('easy', 'Which of these is not a U.S. state?',
         'Alabama', 'Alberta', 'Alaska', 'Arizona', 2),
        ('easy', 'The Amazon Rainforest is primarily located in which continent?',
         'Africa', 'Asia', 'South America', 'Australia', 3),
        ('easy', 'Which of these cities is not a national capital?',
         'Sydney', 'Canberra', 'Washington D.C.', 'London', 1),
        ('easy', 'What is the smallest continent by land area?',
         'Antarctica', 'Europe', 'Australia', 'South America', 3),
        ('easy', 'Which country has the most time zones?',
         'United States', 'Russia', 'China', 'Canada', 2),
        ('easy', 'The Statue of Liberty is located in which U.S. state?',
         'California', 'New York', 'Florida', 'Texas', 2),
        ('easy', 'Which of these countries is landlocked?',
         'Italy', 'Switzerland', 'Spain', 'Greece', 2),
        ('easy', 'The Panama Canal connects which two oceans?', 'Atlantic and Indian',
         'Pacific and Indian', 'Atlantic and Pacific', 'Arctic and Pacific', 3),
        ('easy', 'Which of these is not a Scandinavian country?',
         'Norway', 'Finland', 'Denmark', 'Estonia', 4),
        ('easy', 'What is the capital of Brazil?', 'Rio de Janeiro',
         'São Paulo', 'Brasília', 'Buenos Aires', 3),
        ('easy', 'Which U.S. state is known as the "Sunshine State"?',
         'California', 'Texas', 'Hawaii', 'Florida', 4),
        ('easy', 'The Nile River flows into which body of water?',
         'Mediterranean Sea', 'Red Sea', 'Indian Ocean', 'Atlantic Ocean', 1),
        ('easy', 'Which country is shaped like a boot?',
         'Greece', 'Italy', 'Portugal', 'Spain', 2),
        ('easy', 'What is the capital of South Africa?', 'Johannesburg',
         'Cape Town', 'Pretoria', 'All of the above', 4),
        ('easy', 'Which of these countries is not in South America?',
         'Chile', 'Colombia', 'Guyana', 'Belize', 4),
        ('easy', 'The Dead Sea is bordered by which two countries?', 'Egypt and Israel',
         'Israel and Jordan', 'Jordan and Saudi Arabia', 'Syria and Lebanon', 2),
        ('easy', 'Which continent is the most populous?',
         'Africa', 'Asia', 'Europe', 'North America', 2),
        ('easy', 'What is the capital of Egypt?',
         'Alexandria', 'Cairo', 'Luxor', 'Giza', 2),
        ('easy', 'Which of these countries is an island nation?',
         'Thailand', 'Philippines', 'Vietnam', 'Cambodia', 2),
        ('easy', 'The Grand Canyon is located in which U.S. state?',
         'Colorado', 'Utah', 'Arizona', 'Nevada', 3),
        ('easy', 'Which of these cities is located in the Southern Hemisphere?',
         'Miami', 'Sydney', 'Hong Kong', 'Dubai', 2),
        ('easy', 'What is the capital of Argentina?',
         'Buenos Aires', 'Rio de Janeiro', 'Santiago', 'Lima', 1),
        ('easy', 'Which of these countries does not border Germany?',
         'France', 'Poland', 'Spain', 'Austria', 3),
        ('easy', 'The Andes mountain range runs through which continent?',
         'North America', 'Africa', 'South America', 'Asia', 3),
        ('easy', 'Which of these is not one of the Great Lakes?',
         'Michigan', 'Huron', 'Ontario', 'Champlain', 4),
        ('easy', 'What is the capital of China?',
         'Shanghai', 'Beijing', 'Hong Kong', 'Guangzhou', 2),
        ('easy', 'Which of these countries is not in Africa?',
         'Nigeria', 'Kenya', 'Pakistan', 'Ethiopia', 3),
        ('easy', 'The island of Bali is part of which country?',
         'Thailand', 'Malaysia', 'Indonesia', 'Philippines', 3),
        ('easy', 'Which of these cities is not in Europe?',
         'Vienna', 'Prague', 'Zurich', 'Toronto', 4),
        ('easy', 'What is the capital of Spain?',
         'Barcelona', 'Seville', 'Madrid', 'Valencia', 3),
        ('easy', 'Which country is both in Europe and Asia?',
         'Greece', 'Turkey', 'Egypt', 'Italy', 2),
        ('easy', 'The Maldives are located in which ocean?',
         'Atlantic', 'Indian', 'Pacific', 'Arctic', 2),
        ('easy', 'Which of these countries is the smallest by land area?',
         'Monaco', 'Vatican City', 'San Marino', 'Liechtenstein', 2),
        ('easy', 'What is the capital of New Zealand?', 'Auckland',
         'Christchurch', 'Wellington', 'Queenstown', 3),
        ('easy', 'Which of these U.S. states borders Canada?',
         'Ohio', 'Minnesota', 'Pennsylvania', 'Indiana', 2),
        ('easy', 'The Gobi Desert is primarily located in which country?',
         'India', 'China', 'Mongolia', 'Both B and C', 4),
        ('easy', 'Which of these cities is not in Asia?',
         'Bangkok', 'Mumbai', 'Seoul', 'Cairo', 4),
        ('easy', 'What is the capital of Russia?',
         'St. Petersburg', 'Moscow', 'Kiev', 'Novosibirsk', 2),
        ('easy', 'Which of these countries does not border the Mediterranean Sea?',
         'Algeria', 'Libya', 'Morocco', 'Nigeria', 4),
        ('easy', 'What is the capital of France?',
         'Berlin', 'Madrid', 'Paris', 'Rome', 3),
        ('easy', 'Which is the largest ocean on Earth?',
         'Atlantic', 'Indian', 'Arctic', 'Pacific', 4),
    ]

    medium_questions = [
        ('medium', 'Which country has the longest coastline?',
            'Russia', 'Canada', 'Indonesia', 'Australia', 2),
        ('medium', 'The Strait of Gibraltar separates which two continents?',
         'Europe and Africa', 'Asia and Africa', 'North and South America', 'Europe and Asia', 1),
        ('medium', 'Which of these countries was not part of the former Yugoslavia?',
         'Croatia', 'Slovenia', 'Albania', 'Montenegro', 3),
        ('medium', 'Lake Titicaca is located on the border of which two countries?',
         'Chile and Argentina', 'Peru and Bolivia', 'Brazil and Paraguay', 'Colombia and Venezuela', 2),
        ('medium', 'Which of these African countries was never colonized?',
         'Ethiopia', 'Kenya', 'Nigeria', 'South Africa', 1),
        ('medium', 'The Atacama Desert is located in which country?',
         'Argentina', 'Peru', 'Chile', 'Brazil', 3),
        ('medium', 'Which of these cities is located at the highest elevation?',
         'Denver', 'Bogotá', 'Kathmandu', 'Quito', 4),
        ('medium', 'The Yangtze River flows through which country?',
         'India', 'China', 'Vietnam', 'Thailand', 2),
        ('medium', 'Which of these countries does not have a monarchy?',
         'Sweden', 'Norway', 'Denmark', 'Finland', 4),
        ('medium', 'The Suez Canal connects which two bodies of water?', 'Mediterranean Sea and Red Sea',
         'Atlantic Ocean and Pacific Ocean', 'Red Sea and Indian Ocean', 'Mediterranean Sea and Black Sea', 1),
        ('medium', 'Which of these countries is not in the Middle East?',
         'Qatar', 'Oman', 'Azerbaijan', 'Jordan', 3),
        ('medium', 'The island of Tasmania belongs to which country?',
         'New Zealand', 'Papua New Guinea', 'Australia', 'Indonesia', 3),
        ('medium', 'Which of these countries was not part of the Soviet Union?',
         'Ukraine', 'Belarus', 'Poland', 'Georgia', 3),
        ('medium', 'The Alps mountain range does not pass through which country?',
         'France', 'Germany', 'Spain', 'Austria', 3),
        ('medium', 'Which of these cities is not located on the Mississippi River?',
         'St. Louis', 'New Orleans', 'Chicago', 'Memphis', 3),
        ('medium', 'The Kalahari Desert is primarily located in which country?',
         'Algeria', 'South Africa', 'Botswana', 'Namibia', 3),
        ('medium', 'Which of these countries does not border China?',
         'Myanmar', 'Laos', 'Cambodia', 'Vietnam', 3),
        ('medium', 'The island of Sicily belongs to which country?',
         'Greece', 'Italy', 'Spain', 'Croatia', 2),
        ('medium', 'Which of these U.S. states does not border Mexico?',
         'Arizona', 'New Mexico', 'Texas', 'Nevada', 4),
        ('medium', 'The Mekong River flows through which capital city?',
         'Bangkok', 'Hanoi', 'Phnom Penh', 'Vientiane', 3),
        ('medium', 'Which of these countries was not part of the Roman Empire?',
         'England', 'France', 'Germany', 'Russia', 4),
        ('medium', 'The Drake Passage is located between which two land masses?', 'Greenland and Iceland',
         'Africa and Madagascar', 'South America and Antarctica', 'Alaska and Russia', 3),
        ('medium', 'Which of these countries is not in the Caucasus region?',
         'Armenia', 'Georgia', 'Azerbaijan', 'Kazakhstan', 4),
        ('medium', 'The island of Borneo is shared by which three countries?', 'Thailand, Malaysia, Singapore',
         'Indonesia, Malaysia, Brunei', 'Philippines, Indonesia, Malaysia', 'Vietnam, Cambodia, Thailand', 2),
        ('medium', 'Which of these countries was not part of the British Empire?',
         'India', 'South Africa', 'Thailand', 'Australia', 3),
        ('medium', 'The Pampas grasslands are primarily located in which country?',
         'Brazil', 'Argentina', 'Uruguay', 'Paraguay', 2),
        ('medium', 'Which of these countries does not border the Black Sea?',
         'Romania', 'Bulgaria', 'Greece', 'Turkey', 3),
        ('medium', 'The island of Corsica belongs to which country?',
         'Italy', 'France', 'Spain', 'Greece', 2),
        ('medium', 'Which of these African countries was not a Portuguese colony?',
         'Angola', 'Mozambique', 'Ghana', 'Guinea-Bissau', 3),
        ('medium', 'The Hindu Kush mountain range is primarily located in which country?',
         'Pakistan', 'Afghanistan', 'India', 'Nepal', 2),
        ('medium', 'Which of these cities is not located on the Danube River?',
         'Vienna', 'Budapest', 'Prague', 'Belgrade', 3),
        ('medium', 'The island of Sri Lanka was formerly known as what?',
         'Burma', 'Ceylon', 'Formosa', 'Siam', 2),
        ('medium', 'Which of these countries does not border the Caspian Sea?',
         'Russia', 'Kazakhstan', 'Uzbekistan', 'Iran', 3),
        ('medium', 'The Great Victoria Desert is located in which country?',
         'South Africa', 'Namibia', 'Australia', 'Chile', 3),
        ('medium', 'Which of these countries was not part of the Austro-Hungarian Empire?',
         'Hungary', 'Czech Republic', 'Romania', 'Slovakia', 3),
        ('medium', 'The island of Cyprus is geographically part of which continent?',
         'Europe', 'Asia', 'Africa', 'Middle East', 2),
        ('medium', 'Which of these countries does not border the Adriatic Sea?',
         'Italy', 'Croatia', 'Greece', 'Albania', 3),
        ('medium', 'The Okavango Delta is located in which country?',
         'Zambia', 'Botswana', 'Namibia', 'Zimbabwe', 2),
        ('medium', 'Which of these countries was not part of the Inca Empire?',
         'Peru', 'Ecuador', 'Chile', 'Brazil', 4),
        ('medium', 'The island of Java is part of which country?',
         'Philippines', 'Indonesia', 'Malaysia', 'Thailand', 2),
        ('medium', 'Which of these U.S. states was not part of the Louisiana Purchase?',
         'Arkansas', 'Missouri', 'Oklahoma', 'Texas', 4),
        ('medium', 'The Karakoram Highway connects which two countries?', 'India and Pakistan',
         'China and Pakistan', 'China and India', 'Afghanistan and Pakistan', 2),
        ('medium', 'Which of these African countries was not a French colony?',
         'Senegal', 'Ivory Coast', 'Cameroon', 'Tanzania', 4),
        ('medium', 'The island of Newfoundland belongs to which country?',
         'United States', 'Canada', 'United Kingdom', 'France', 2),
        ('medium', 'Which of these countries does not border the Baltic Sea?',
         'Poland', 'Germany', 'Denmark', 'Norway', 4),
        ('medium', 'The Dardanelles Strait connects which two bodies of water?', 'Aegean Sea and Black Sea',
         'Mediterranean Sea and Red Sea', 'Adriatic Sea and Ionian Sea', 'North Sea and Baltic Sea', 1),
        ('medium', 'Which of these countries was not part of the Ottoman Empire?',
         'Greece', 'Bulgaria', 'Hungary', 'Russia', 4),
        ('medium', 'The island of Honshu is part of which country?',
         'China', 'Japan', 'South Korea', 'Philippines', 2),
        ('medium', 'Which of these U.S. states does not border the Great Lakes?',
         'Michigan', 'Wisconsin', 'Ohio', 'Pennsylvania', 4),
        ('medium', 'The Trans-Siberian Railway connects which two cities?', 'Moscow and Beijing',
         'Moscow and Vladivostok', 'St. Petersburg and Irkutsk', 'Warsaw and Moscow', 2),
    ]

    difficult_questions = [
        ('difficult', 'Which country has the most islands?',
         'Canada', 'Sweden', 'Indonesia', 'Norway', 2),
        ('difficult', 'The Salar de Uyuni, the world\'s largest salt flat, is located in which country?',
            'Chile', 'Argentina', 'Bolivia', 'Peru', 3),
        ('difficult', 'Which of these countries was not part of the Persian Empire?',
            'Egypt', 'Greece', 'India', 'China', 4),
        ('difficult', 'The Pamir Mountains are primarily located in which country?',
            'Pakistan', 'Afghanistan', 'Tajikistan', 'Kyrgyzstan', 3),
        ('difficult', 'Which of these cities is not located on the Rhine River?',
            'Basel', 'Strasbourg', 'Cologne', 'Munich', 4),
        ('difficult', 'The island of Socotra belongs to which country?',
            'Oman', 'Yemen', 'Somalia', 'Djibouti', 2),
        ('difficult', 'Which of these countries was not part of the Mayan civilization?',
            'Mexico', 'Guatemala', 'Honduras', 'Colombia', 4),
        ('difficult', 'The Great Rift Valley runs through which African lake?',
            'Lake Victoria', 'Lake Tanganyika', 'Lake Malawi', 'All of the above', 4),
        ('difficult', 'Which of these countries does not have territory in the Arctic Circle?',
            'United States', 'Canada', 'Iceland', 'Finland', 3),
        ('difficult', 'The Bab el Mandeb strait connects which two bodies of water?', 'Red Sea and Gulf of Aden',
            'Mediterranean Sea and Red Sea', 'Persian Gulf and Arabian Sea', 'Black Sea and Sea of Marmara', 1),
        ('difficult', 'Which of these African countries was not a Belgian colony?',
            'Rwanda', 'Burundi', 'Democratic Republic of Congo', 'Tanzania', 4),
        ('difficult', 'The island of Réunion is an overseas department of which country?',
            'United Kingdom', 'France', 'Portugal', 'Spain', 2),
        ('difficult', 'Which of these countries was not part of the Mughal Empire?',
            'India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 4),
        ('difficult', 'The Taklamakan Desert is located in which autonomous region?',
            'Tibet', 'Xinjiang', 'Inner Mongolia', 'Guangxi', 2),
        ('difficult', 'Which of these cities is not located on the Volga River?',
            'Moscow', 'Kazan', 'Volgograd', 'Nizhny Novgorod', 1),
        ('difficult', 'The island of Zanzibar belongs to which country?',
            'Kenya', 'Tanzania', 'Mozambique', 'Somalia', 2),
        ('difficult', 'Which of these countries was not part of the Khmer Empire?',
            'Cambodia', 'Laos', 'Thailand', 'Vietnam', 4),
        ('difficult', 'The Dasht-e Kavir is a desert in which country?',
            'Afghanistan', 'Pakistan', 'Iran', 'Iraq', 3),
        ('difficult', 'Which of these countries does not have territory in the Antarctic?',
            'Australia', 'New Zealand', 'Chile', 'South Africa', 4),
        ('difficult', 'The Makassar Strait separates which two islands?', 'Java and Sumatra',
            'Borneo and Sulawesi', 'New Guinea and Timor', 'Luzon and Mindanao', 2),
        ('difficult', 'Which of these African countries was not an Italian colony?',
            'Libya', 'Eritrea', 'Somalia', 'Sudan', 4),
        ('difficult', 'The island of Spitsbergen belongs to which country?',
            'Norway', 'Russia', 'Denmark', 'Sweden', 1),
        ('difficult', 'Which of these countries was not part of the Achaemenid Empire?',
            'Egypt', 'Greece', 'Pakistan', 'Russia', 4),
        ('difficult', 'The Thar Desert is located between which two countries?',
            'India and Pakistan', 'Pakistan and Afghanistan', 'India and Nepal', 'Pakistan and Iran', 1),
        ('difficult', 'Which of these cities is not located on the Ganges River?',
            'Varanasi', 'Patna', 'Allahabad', 'Agra', 4),
        ('difficult', 'The island of Bioko belongs to which country?',
            'Equatorial Guinea', 'Gabon', 'Cameroon', 'Nigeria', 1),
        ('difficult', 'Which of these countries was not part of the Mali Empire?',
            'Mali', 'Senegal', 'Gambia', 'Nigeria', 4),
        ('difficult', 'The Dasht-e Lut is a desert in which country?',
            'Saudi Arabia', 'Iran', 'Iraq', 'Afghanistan', 2),
        ('difficult', 'Which of these countries does not have territory in the tropics?',
            'Brazil', 'India', 'Mexico', 'China', 4),
        ('difficult', 'The Lombok Strait separates which two islands?', 'Java and Bali',
            'Bali and Lombok', 'Lombok and Sumbawa', 'Sumatra and Java', 2),
        ('difficult', 'Which of these African countries was not a German colony?',
            'Tanzania', 'Namibia', 'Cameroon', 'Ethiopia', 4),
        ('difficult', 'The island of Gotland belongs to which country?',
            'Sweden', 'Finland', 'Denmark', 'Norway', 1),
        ('difficult', 'Which of these countries was not part of the Timurid Empire?',
            'Iran', 'Afghanistan', 'Uzbekistan', 'Turkey', 4),
        ('difficult', 'The Kyzylkum Desert is located between which two rivers?',
            'Amu Darya and Syr Darya', 'Tigris and Euphrates', 'Indus and Ganges', 'Nile and Niger', 1),
        ('difficult', 'Which of these cities is not located on the Yangtze River?',
            'Chongqing', 'Wuhan', 'Nanjing', 'Xi\'an', 4),
        ('difficult', 'The island of Bougainville is part of which country?',
            'Papua New Guinea', 'Solomon Islands', 'Vanuatu', 'Fiji', 1),
        ('difficult', 'Which of these countries was not part of the Songhai Empire?',
            'Mali', 'Niger', 'Nigeria', 'Chad', 4),
        ('difficult', 'The Rub\' al Khali desert is primarily located in which country?',
            'Iraq', 'Saudi Arabia', 'Yemen', 'Oman', 2),
        ('difficult', 'Which of these countries does not have territory in the Sahara Desert?',
            'Algeria', 'Libya', 'Egypt', 'Sudan', 4),
        ('difficult', 'The Torres Strait separates which two land masses?', 'Sumatra and Malaysia',
            'Australia and New Guinea', 'Madagascar and Africa', 'Japan and Korea', 2),
        ('difficult', 'Which of these African countries was not a Spanish colony?',
            'Equatorial Guinea', 'Western Sahara', 'Morocco', 'Angola', 4),
        ('difficult', 'The island of Åland belongs to which country?',
            'Sweden', 'Norway', 'Finland', 'Denmark', 3),
        ('difficult', 'Which of these countries was not part of the Gupta Empire?',
            'India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 4),
        ('difficult', 'The Gobi Desert is primarily located in which autonomous region?',
            'Tibet', 'Xinjiang', 'Inner Mongolia', 'Manchuria', 3),
        ('difficult', 'Which of these cities is not located on the Tigris River?',
            'Baghdad', 'Mosul', 'Basra', 'Erbil', 3),
        ('difficult', 'The island of New Caledonia is an overseas territory of which country?',
            'United Kingdom', 'France', 'Australia', 'New Zealand', 2),
        ('difficult', 'Which of these countries was not part of the Ashanti Empire?',
            'Ghana', 'Togo', 'Ivory Coast', 'Nigeria', 4),
        ('difficult', 'The Danakil Depression is located in which country?',
            'Eritrea', 'Ethiopia', 'Djibouti', 'Somalia', 2),
        ('difficult', 'Which of these countries does not have territory in the Andes Mountains?',
            'Colombia', 'Venezuela', 'Ecuador', 'Peru', 2),
        ('difficult', 'The Makran Coastal Range is located in which two countries?', 'Iran and Pakistan',
            'Pakistan and Afghanistan', 'Afghanistan and Iran', 'India and Pakistan', 1),
        ('difficult', 'Which of these African countries was not a Dutch colony?',
            'South Africa', 'Ghana', 'Angola', 'Mozambique', 4)
    ]

    all_questions = easy_questions + medium_questions + difficult_questions

    cursor.executemany('''
    INSERT INTO questions (difficulty, question_text, option1, option2, option3, option4, correct_answer)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', all_questions)

    conn.commit()
    conn.close()
    print("Database 'geography_quiz.db' created successfully with 150 general questions!")


if __name__ == '__main__':
    create_database()
