import sqlite3


def create_database():

    conn = sqlite3.connect('history_quiz.db')
    cursor = conn.cursor()

    cursor.execute('DROP TABLE IF EXISTS questions')

    cursor.execute('''
    CREATE TABLE IF NOT EXISTS questions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        difficulty TEXT CHECK(difficulty IN ('easy', 'medium', 'difficult')),
        question_text TEXT NOT NULL,
        option1 TEXT NOT NULL,
        option2 TEXT NOT NULL,
        option3 TEXT NOT NULL,
        option4 TEXT NOT NULL,
        correct_answer INTEGER CHECK(correct_answer BETWEEN 1 AND 4)
    )
    ''')

    # EasyHistory Questions
    easy_questions = [
        ('easy', "In which year did Christopher Columbus reach the Americas?",
         "1492", "1507", "1620", "1776", 1),
        ('easy', "Who was the first president of the United States?",
         "George Washington", "Thomas Jefferson", "John Adams", "Benjamin Franklin", 1),
        ('easy', "What was the name of the ship that carried the Pilgrims to America?",
         "The Mayflower", "The Santa Maria", "The Victory", "The Endeavour", 1),
        ('easy', "Which war was fought between the North and South in the United States?",
         "World War I", "World War II", "Civil War", "Revolutionary War", 3),
        ('easy', "Who was the Queen of England during World War II?",
         "Queen Victoria", "Queen Elizabeth I", "Queen Elizabeth II", "Queen Mary", 3),
        ('easy', "Which ancient civilization built the pyramids of Giza?",
         "Roman", "Greek", "Egyptian", "Persian", 3),
        ('easy', "What was the name of the Roman Colosseum?",
         "Flavian Amphitheatre", "Pantheon", "Forum Romanum", "Circus Maximus", 1),
        ('easy', "Who painted the Mona Lisa?", "Vincent van Gogh",
         "Leonardo da Vinci", "Pablo Picasso", "Claude Monet", 2),
        ('easy', "Which famous playwright wrote 'Romeo and Juliet'?", "William Shakespeare",
         "George Bernard Shaw", "Arthur Miller", "Tennessee Williams", 1),
        ('easy', "What was the Renaissance?", "A period of war",
         "A period of artistic and intellectual rebirth", "A religious movement", "A political revolution", 2),
        ('easy', "In which country did the Industrial Revolution begin?",
         "France", "Germany", "England", "United States", 3),
        ('easy', "Who invented the telephone?", "Thomas Edison",
         "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi", 2),
        ('easy', "What year did World War I begin?",
         "1914", "1918", "1939", "1945", 1),
        ('easy', "Who was the leader of the Soviet Union during World War II?",
         "Vladimir Lenin", "Joseph Stalin", "Nikita Khrushchev", "Mikhail Gorbachev", 2),
        ('easy', "Which country was defeated in World War II?",
         "France", "United Kingdom", "Germany", "Soviet Union", 3),
        ('easy', "What event started World War II?", "Invasion of Poland",
         "Bombing of Pearl Harbor", "Treaty of Versailles", "Rise of Hitler", 1),
        ('easy', "Who was the first man to walk on the moon?",
         "Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Alan Shepard", 2),
        ('easy', "What was the Cold War?", "A war fought in cold climates", "A period of political tension between the United States and the Soviet Union",
         "A war fought with new, cold weapons", "A war fought over cold resources", 2),
        ('easy', "Which country built the Great Wall?",
         "India", "China", "Japan", "Korea", 2),
        ('easy', "Who was the first emperor of Rome?",
         "Julius Caesar", "Augustus", "Nero", "Constantine", 2),
        ('easy', "What is the name of the ancient Egyptian writing system?",
         "Cuneiform", "Hieroglyphics", "Aramaic", "Sanskrit", 2),
        ('easy', "In which modern-day country is Mesopotamia located?",
         "Egypt", "Iraq", "Turkey", "Iran", 2),
        ('easy', "Who was the Greek god of war?",
         "Zeus", "Poseidon", "Ares", "Apollo", 3),
        ('easy', "Which empire built the Appian Way?",
         "Greek", "Roman", "Persian", "Egyptian", 2),
        ('easy', "Who wrote the 'Iliad' and the 'Odyssey'?",
         "Plato", "Aristotle", "Homer", "Socrates", 3),
        ('easy', "What was the name of the ship Charles Darwin sailed on?",
         "The Beagle", "The Victory", "The Endeavour", "The Golden Hind", 1),
        ('easy', "Which war is known as 'The War to End All Wars'?", "World War I",
         "World War II", "The Napoleonic Wars", "The Crimean War", 1),
        ('easy', "Who developed the theory of relativity?", "Isaac Newton",
         "Albert Einstein", "Stephen Hawking", "Galileo Galilei", 2),
        ('easy', "What was the Manhattan Project?", "A secret city",
         "A military operation to develop the atomic bomb", "A plan to rebuild New York", "An art exhibition", 2),
        ('easy', "In which year did the Berlin Wall fall?",
         "1987", "1989", "1991", "1993", 2),
        ('easy', "Who was the leader of Nazi Germany?", "Joseph Stalin",
         "Adolf Hitler", "Benito Mussolini", "Winston Churchill", 2),
        ('easy', "What was the Holocaust?", "A religious pilgrimage",
         "The genocide of European Jews by the Nazis", "A series of battles", "A political debate", 2),
        ('easy', "Which country did Gandhi lead to independence?",
         "Pakistan", "India", "Bangladesh", "Sri Lanka", 2),
        ('easy', "Who was the first woman Prime Minister of the United Kingdom?",
         "Margaret Thatcher", "Theresa May", " इंदिरा Gandhi", "Golda Meir", 1),
        ('easy', "What was the name of the first artificial satellite launched into space?",
         "Sputnik 1", "Explorer 1", "Voyager 1", "Apollo 11", 1),
        ('easy', "Which American president was assassinated in Dallas, Texas in 1963?",
         "Franklin D. Roosevelt", "John F. Kennedy", "Lyndon B. Johnson", "Richard Nixon", 2),
        ('easy', "What was the Watergate Scandal?", "A political robbery",
         "A series of political scandals involving the Nixon administration", "A water pollution incident", "A housing crisis", 2),
        ('easy', "Who gave the 'I Have a Dream' speech?",
         "Martin Luther King Jr.", "Malcolm X", "Rosa Parks", "Jesse Jackson", 1),
        ('easy', "Which country was divided into East and West during the Cold War?",
         "Korea", "Vietnam", "Germany", "China", 3),
        ('easy', "What year did the Titanic sink?",
         "1910", "1912", "1914", "1916", 2),
        ('easy', "Who was the first female pilot to fly solo across the Atlantic Ocean?",
         "Bessie Coleman", "Amelia Earhart", "Jacqueline Cochran", "Harriet Quimby", 2),
        ('easy', "What was the name of the ancient trade route connecting Europe and Asia?",
         "Silk Road", "Spice Road", "Golden Road", "Amber Road", 1),
        ('easy', "Which religion was founded by Siddhartha Gautama?",
         "Hinduism", "Buddhism", "Jainism", "Sikhism", 2),
        ('easy', "Who painted the ceiling of the Sistine Chapel?",
         "Raphael", "Michelangelo", "Donatello", "Titian", 2),
        ('easy', "What was the name of the French Revolution's most famous leader?",
         "Louis XVI", "Napoleon Bonaparte", "Maximilien Robespierre", "Jean-Paul Marat", 2),
        ('easy', "Which war was fought between Britain and France in the 18th century?",
         "The Hundred Years' War", "The War of the Roses", "The Seven Years' War", "The Napoleonic Wars", 3),
        ('easy', "Who wrote 'Pride and Prejudice'?", "Jane Austen",
         "Charlotte Brontë", "Emily Brontë", "George Eliot", 1),
        ('easy', "What was the name of the battle in which Napoleon was finally defeated?",
         "Battle of Waterloo", "Battle of Austerlitz", "Battle of Trafalgar", "Battle of Borodino", 1),
        ('easy', "Which country colonized Brazil?",
         "Spain", "Portugal", "France", "Netherlands", 2),
        ('easy', "Who is known as the 'Father of Modern Physics'?", "Isaac Newton",
         "Albert Einstein", "Galileo Galilei", "Stephen Hawking", 3),
    ]

    medium_questions = [
        ('medium', "Which ancient civilization developed the first known alphabet?",
         "Sumerians", "Egyptians", "Phoenicians", "Babylonians", 3),
        ('medium', "Who was the first emperor of China?",
         "Confucius", "Qin Shi Huang", "Lao Tzu", "Mao Zedong", 2),
        ('medium', "Which famous battle was fought in 1066?", "Battle of Hastings",
         "Battle of Waterloo", "Battle of Gettysburg", "Battle of Thermopylae", 1),
        ('medium', "Who led the Norman conquest of England?", "William the Conqueror",
         "Richard the Lionheart", "Henry VIII", "Alfred the Great", 1),
        ('medium', "What was the Magna Carta?", "A religious text", "A peace treaty",
         "A document limiting the power of the English monarch", "A declaration of independence", 3),
        ('medium', "Which European country was the first to industrialize?",
         "France", "Germany", "Great Britain", "Netherlands", 3),
        ('medium', "Who invented the steam engine?", "James Watt",
         "Thomas Edison", "Gottlieb Daimler", "Rudolf Diesel", 1),
        ('medium', "What was the cause of the American Civil War?",
         "Slavery", "Taxation", "States' rights", "All of the above", 4),
        ('medium', "Who was the president of the Confederate States of America?",
         "Robert E. Lee", "Stonewall Jackson", "Jefferson Davis", "George McClellan", 3),
        ('medium', "Which event is considered the turning point of World War II in Europe?",
         "Battle of Stalingrad", "Battle of Normandy", "Battle of Britain", "Battle of the Bulge", 1),
        ('medium', "What was the Marshall Plan?", "A military strategy", "An economic recovery plan for Europe after World War II",
         "A treaty between the United States and the Soviet Union", "A plan to rebuild Japan", 2),
        ('medium', "Who led the Cuban Revolution?", "Fidel Castro",
         "Che Guevara", "Raul Castro", "Juan Perón", 1),
        ('medium', "Which country launched the first artificial satellite, Sputnik 1?",
         "United States", "Soviet Union", "Germany", "United Kingdom", 2),
        ('medium', "What was the primary goal of the Civil Rights Movement in the United States?", "To gain independence from Britain",
         "To end racial segregation and discrimination", "To promote free trade", "To establish a socialist government", 2),
        ('medium', "Who was the leader of the apartheid regime in South Africa?",
         "Nelson Mandela", "F.W. de Klerk", "P.W. Botha", "Robert Mugabe", 3),
        ('medium', "Which war is also known as the 'Forgotten War'?",
         "Korean War", "Vietnam War", "Persian Gulf War", "Afghan War", 1),
        ('medium', "What was the name of the series of conflicts between the United States and Vietnam?",
         "Korean War", "Vietnam War", "Cold War", "World War II", 2),
        ('medium', "Which country did the 'Arab Spring' uprisings begin in?",
         "Egypt", "Tunisia", "Libya", "Yemen", 2),
        ('medium', "Who was the first woman to serve on the U.S. Supreme Court?",
         "Sandra Day O'Connor", "Ruth Bader Ginsburg", "Sonia Sotomayor", "Elena Kagan", 1),
        ('medium', "What was the name of the peace agreement signed between Israel and Egypt in 1978?",
         "Camp David Accords", "Oslo Accords", "Abraham Accords", "Wye River Memorandum", 1),
        ('medium', "Which empire built Machu Picchu?",
         "Aztec", "Inca", "Maya", "Olmec", 2),
        ('medium', "Who was the first European to sail around the tip of Africa?",
         "Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "James Cook", 2),
        ('medium', "What was the name of the ship that sank in 1912 on its maiden voyage?",
         "Lusitania", "Titanic", "Britannic", "Olympic", 2),
        ('medium', "Who developed the theory of evolution by natural selection?",
         "Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Marie Curie", 2),
        ('medium', "Which country was divided by an Iron Curtain during the Cold War?",
         "China", "Korea", "Germany", "Vietnam", 3),
        ('medium', "What was the purpose of the Berlin Wall?", "To keep people in East Germany from fleeing to West Germany",
         "To protect West Germany from communist influence", "To divide the city for administrative purposes", "To symbolize the end of World War II", 1),
        ('medium', "Who led the Allied forces on D-Day?", "George S. Patton",
         "Dwight D. Eisenhower", "Bernard Montgomery", "Douglas MacArthur", 2),
        ('medium', "What was the name of the project to develop the first nuclear weapons?",
         "Manhattan Project", "Trinity Project", "Overlord Project", "Apollo Project", 1),
        ('medium', "Which country experienced a revolution in 1979 that led to the establishment of an Islamic Republic?",
         "Egypt", "Iran", "Saudi Arabia", "Iraq", 2),
        ('medium', "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
         "Joseph Stalin", "Nikita Khrushchev", "Leonid Brezhnev", "Mikhail Gorbachev", 2),
        ('medium', "What was the name of the series of protests in China in 1989?", "May Fourth Movement",
         "Cultural Revolution", "Tiananmen Square Protests", "Great Leap Forward", 3),
        ('medium', "Which treaty ended World War I?", "Treaty of Versailles",
         "Treaty of Paris", "Treaty of Brest-Litovsk", "Treaty of Tordesillas", 1),
        ('medium', "Who was the last Tsar of Russia?", "Nicholas I",
         "Alexander II", "Alexander III", "Nicholas II", 4),
        ('medium', "Which empire fought in the Punic Wars?", "Roman Empire",
         "Persian Empire", "Ottoman Empire", "Byzantine Empire", 1),
        ('medium', "Who was the Carthaginian general who crossed the Alps to attack Rome?",
         "Scipio Africanus", "Hannibal Barca", "Hasdrubal Barca", "Mago Barca", 2),
        ('medium', "What was the name of the ancient library in Egypt?", "Library of Alexandria",
         "Library of Pergamum", "Library of Celsus", "Royal Library of Ashurbanipal", 1),
        ('medium', "Which philosopher was sentenced to death in ancient Athens?",
         "Plato", "Aristotle", "Socrates", "Diogenes", 3),
        ('medium', "Who was the founder of the Mongol Empire?",
         "Kublai Khan", "Genghis Khan", "Tamerlane", "Hulegu Khan", 2),
        ('medium', "Which European explorer reached the Americas before Christopher Columbus?",
         "Leif Erikson", "Marco Polo", "Ferdinand Magellan", "Amerigo Vespucci", 1),
        ('medium', "What was the name of the Spanish conquest of the Aztec Empire?",
         "Conquest of Peru", "Conquest of Mexico", "Conquest of Chile", "Conquest of Argentina", 2),
        ('medium', "Who was the first English monarch of the House of Tudor?",
         "Henry VII", "Henry VIII", "Elizabeth I", "Edward VI", 1),
        ('medium', "Which religious movement began in Germany in the 16th century?",
         "The Renaissance", "The Reformation", "The Enlightenment", "The Counter-Reformation", 2),
        ('medium', "Who was the French king during the French Revolution?",
         "Louis XIV", "Louis XV", "Louis XVI", "Louis XVIII", 3),
        ('medium', "Which document declared the independence of the American colonies from Britain?", "The Magna Carta",
         "The Declaration of Independence", "The Bill of Rights", "The Articles of Confederation", 2),
        ('medium', "Who was the commander-in-chief of the Continental Army during the American Revolution?",
         "Thomas Jefferson", "George Washington", "John Adams", "Benjamin Franklin", 2),
        ('medium', "What was the name of the ship that was sunk in the Boston Tea Party?",
         "The Intrepid", "The Endeavour", "The Dartmouth", "The Liberty", 3),
        ('medium', "Which battle is considered the turning point of the American Revolutionary War?",
         "Battle of Lexington", "Battle of Concord", "Battle of Saratoga", "Battle of Yorktown", 3),
        ('medium', "Who was the second president of the United States?",
         "John Adams", "Thomas Jefferson", "James Madison", "James Monroe", 1),
        ('medium', "Which war was fought between Great Britain and China over opium trade?",
         "Opium Wars", "Boxer Rebellion", "Sino-Japanese War", "Taiping Rebellion", 1),
    ]

    difficult_questions = [
        ('difficult', "Which ancient civilization used the dromedar as a beast of war?",
         "Persians", "Egyptians", "Romans", "Greeks", 1),
        ('difficult', "Who was the founder of the Achaemenid Empire?",
         "Cyrus the Great", "Darius I", "Xerxes I", "Alexander the Great", 1),
        ('difficult', "Which battle marked the end of the Roman Republic and the beginning of the Roman Empire?",
         "Battle of Actium", "Battle of Cannae", "Battle of Pharsalus", "Battle of Zama", 1),
        ('difficult', "Who was the first emperor of the Qin Dynasty?",
         "Lao Tzu", "Confucius", "Qin Shi Huang", "Mencius", 3),
        ('difficult', "Which Chinese dynasty implemented the civil service examination system?",
         "Han Dynasty", "Tang Dynasty", "Song Dynasty", "Ming Dynasty", 1),
        ('difficult', "What was the name of the Viking who led an expedition to North America?",
         "Erik the Red", "Leif Erikson", "Bjorn Ironside", "Ivar the Boneless", 2),
        ('difficult', "Which crusade resulted in the sack of Constantinople?",
         "First Crusade", "Second Crusade", "Third Crusade", "Fourth Crusade", 4),
        ('difficult', "Who was the Holy Roman Emperor who initiated the Investiture Controversy?",
         "Henry III", "Henry IV", "Frederick Barbarossa", "Otto I", 2),
        ('difficult', "Which English king signed the Magna Carta?",
         "John I", "Henry II", "Richard I", "Edward I", 1),
        ('difficult', "What was the name of the plague that devastated Europe in the 14th century?",
         "Bubonic Plague", "Black Death", "Great Plague of London", "Justinian's Plague", 2),
        ('difficult', "Which Italian city-state was a major center of Renaissance art and culture?",
         "Rome", "Florence", "Venice", "Milan", 2),
        ('difficult', "Who painted the 'Birth of Venus'?",
         "Leonardo da Vinci", "Sandro Botticelli", "Raphael", "Titian", 2),
        ('difficult', "Which treaty ended the Thirty Years' War?", "Treaty of Westphalia",
         "Treaty of Utrecht", "Treaty of Versailles", "Treaty of Tordesillas", 1),
        ('difficult', "Who was the 'Sun King' of France?",
         "Louis XIII", "Louis XIV", "Louis XV", "Louis XVI", 2),
        ('difficult', "Which Russian ruler abolished serfdom?",
         "Catherine the Great", "Peter the Great", "Alexander II", "Nicholas I", 3),
        ('difficult', "What was the name of the war fought between Britain and France in the 18th century?",
         "The Hundred Years' War", "The War of the Roses", "The Seven Years' War", "The Napoleonic Wars", 3),
        ('difficult', "Who wrote 'The Wealth of Nations'?", "Karl Marx",
         "Adam Smith", "John Maynard Keynes", "David Ricardo", 2),
        ('difficult', "Which event sparked the French Revolution?", "Storming of the Bastille",
         "Tennis Court Oath", "Execution of Louis XVI", "Reign of Terror", 1),
        ('difficult', "Who was the leader of the Haitian Revolution?", "Toussaint Louverture",
         "Jean-Jacques Dessalines", "Henri Christophe", "Alexandre Pétion", 1),
        ('difficult', "Which battle is considered Napoleon's greatest victory?", "Battle of Waterloo",
         "Battle of Austerlitz", "Battle of Trafalgar", "Battle of Borodino", 2),
        ('difficult', "What was the name of the agreement that divided the Americas between Spain and Portugal?",
         "Treaty of Westphalia", "Treaty of Utrecht", "Treaty of Versailles", "Treaty of Tordesillas", 4),
        ('difficult', "Which African kingdom was known for its gold trade and its queen, Makeda?",
         "Kingdom of Kush", "Kingdom of Aksum", "Kingdom of Zimbabwe", "Kingdom of Sheba", 4),
        ('difficult', "Who was the founder of the Mughal Empire?",
         "Akbar", "Shah Jahan", "Babur", "Aurangzeb", 3),
        ('difficult', "Which Japanese shogunate came to power after the Sengoku period?",
         "Kamakura Shogunate", "Ashikaga Shogunate", "Tokugawa Shogunate", "Edo Shogunate", 3),
        ('difficult', "What was the name of the Chinese admiral who led treasure fleets in the early Ming Dynasty?",
         "Zheng He", "Zhang Qian", "Sun Tzu", "Wu Zetian", 1),
        ('difficult', "Which war was fought in the 19th century over control of the Crimean Peninsula?",
         "Russo-Turkish War", "Crimean War", "Napoleonic Wars", "Seven Years' War", 2),
        ('difficult', "Who was the British Prime Minister during World War I?",
         "Herbert Asquith", "David Lloyd George", "Winston Churchill", "Neville Chamberlain", 2),
        ('difficult', "Which country was known as 'The Sick Man of Europe' in the late 19th and early 20th centuries?",
         "Spain", "Ottoman Empire", "Austria-Hungary", "Russia", 2),
        ('difficult', "What was the name of the treaty that ended World War I and imposed harsh terms on Germany?",
         "Treaty of Brest-Litovsk", "Treaty of Versailles", "Treaty of Trianon", "Treaty of Saint-Germain-en-Laye", 2),
        ('difficult', "Who developed the concept of 'total war'?", "Carl von Clausewitz",
         "Alfred Thayer Mahan", "Erich Ludendorff", "Helmuth von Moltke the Elder", 3),
        ('difficult', "Which battle is considered the turning point of the war in the Pacific during World War II?",
         "Battle of Midway", "Battle of Guadalcanal", "Battle of Leyte Gulf", "Battle of Iwo Jima", 1),
        ('difficult', "What was the name of the international organization formed after World War I to prevent future wars?",
         "League of Nations", "United Nations", "Warsaw Pact", "NATO", 1),
        ('difficult', "Which country was the first to grant women the right to vote?",
         "United States", "United Kingdom", "New Zealand", "Australia", 3),
        ('difficult', "Who was the leader of the Indian National Congress during the Indian independence movement?",
         "Jawaharlal Nehru", "Mahatma Gandhi", "Sardar Vallabhbhai Patel", "Subhas Chandra Bose", 2),
        ('difficult', "What was the name of the policy of racial segregation in South Africa?",
         "Apartheid", "Segregation", "Racial Discrimination", "Jim Crow Laws", 1),
        ('difficult', "Which event led to the United States' entry into World War II?",
         "Sinking of the Lusitania", "Attack on Pearl Harbor", "Zimmerman Telegram", "Invasion of Poland", 2),
        ('difficult', "Who was the leader of the Soviet Union during the Cuban Missile Crisis?",
         "Joseph Stalin", "Nikita Khrushchev", "Leonid Brezhnev", "Mikhail Gorbachev", 2),
        ('difficult', "What was the name of the program of economic and political reforms initiated by Mikhail Gorbachev in the Soviet Union?",
         "Glasnost and Perestroika", "New Economic Policy", "Five-Year Plans", "De-Stalinization", 1),
        ('difficult', "Which conflict is known as the 'Six-Day War'?",
         "Yom Kippur War", "Persian Gulf War", "Arab-Israeli War", "Iran-Iraq War", 3),
        ('difficult', "What was the name of the agreement that led to the end of apartheid in South Africa?",
         "Groote Schuur Minute", "Pretoria Minute", "Codesa Talks", "Multi-Party Negotiating Process", 2),
        ('difficult', "Which country was the site of the ancient city of Carthage?",
         "Egypt", "Tunisia", "Libya", "Algeria", 2),
        ('difficult', "Who developed the heliocentric theory of the solar system?",
         "Galileo Galilei", "Johannes Kepler", "Nicolaus Copernicus", "Isaac Newton", 3),
        ('difficult', "What was the name of the dynasty that ruled China during the voyages of Zheng He?",
         "Han Dynasty", "Tang Dynasty", "Ming Dynasty", "Qing Dynasty", 3),
        ('difficult', "Which war is associated with the phrase 'Remember the Alamo!'?",
         "Mexican-American War", "Texas Revolution", "Spanish-American War", "American Civil War", 2),
        ('difficult', "Who was the first woman to fly in space?", "Valentina Tereshkova",
         "Sally Ride", "Svetlana Savitskaya", "Judith Resnik", 1),
        ('difficult', "What was the name of the ancient library in Mesopotamia?", "Library of Alexandria",
         "Library of Pergamum", "Royal Library of Ashurbanipal", "House of Wisdom", 3),
        ('difficult', "Which philosopher is known for the concept of the 'social contract'?",
         "Plato", "Aristotle", "John Locke", "Immanuel Kant", 3),
        ('difficult', "What was the name of the series of religious wars between Christians and Muslims over the Holy Land?",
         "The Crusades", "The Reconquista", "The Jihad", "The Thirty Years' War", 1),
        ('difficult', "Who was the Aztec emperor when the Spanish conquistadors arrived?",
         "Montezuma I", "Ahuitzotl", "Montezuma II", "Cuauhtémoc", 3),
        ('difficult', "Which treaty established the principle of 'cuius regio, eius religio'?",
         "Peace of Augsburg", "Edict of Nantes", "Peace of Westphalia", "Treaty of Tordesillas", 1),
        ('difficult', "Who is considered the father of modern genetics?",
         "Charles Darwin", "Gregor Mendel", "James Watson", "Francis Crick", 2),
    ]

    all_questions = easy_questions + medium_questions + difficult_questions

    cursor.executemany('''
    INSERT INTO questions (difficulty, question_text, option1, option2, option3, option4, correct_answer)
    VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', all_questions)

    conn.commit()
    conn.close()
    print("Database 'history_quiz.db' created successfully with 150 general questions!")


if __name__ == '__main__':
    create_database()
